---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 2
    memory: 1024

platforms:
- name: ubuntu-12.04
  run_list: ["recipe[apt]"]
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: centos-6.4
  run_list: ["recipe[yum::epel]"]
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list:
  - recipe[rightscale_tag::default]
  - recipe[rs-haproxy::default]
  attributes:
    cloud:
      provider: 'vagrant'
    rs-haproxy:
      pools: "default, app1, app2"
      stats_uri: '/haproxy-status'
      health_check_uri: '/'
      algorithm: 'roundrobin'
    rightscale:
      instance_uuid: '12345UUID'
