---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 2
    memory: 1024
  network:
    - ["private_network", {ip: "192.0.2.2"}]

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
- name: centos-6.5
  run_list:
  - recipe[yum::epel]
  driver_config:
    box: opscode-centos-6.5
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

# Tests the basic HAProxy configuration, load balancer related machine tags set on the server, and
# the HAProxy collectd monitoring configuration. The HAProxy configuration is verified by ensuring
# the HAProxy parameters in the haproxy.cfg file are set up as expected.
#
suites:
- name: default
  run_list:
  - recipe[rs-haproxy::default]
  - recipe[rs-haproxy::tags]
  - recipe[rs-haproxy::collectd]
  attributes:
    rightscale:
      instance_uuid: '01-ABCDEFGH0123'
    cloud:
      provider: 'vagrant'
      public_ips: ['192.0.2.2']
    rs-haproxy:
      pools: ['test_example', 'appserver', 'example']
      stats_uri: '/haproxy-status'
      stats_user: 'statsuser'
      stats_password: 'statspass'
      health_check_uri: '/'
      session_stickiness: true

# Tests the HAProxy frontend and backend configuration and SSL by setting up fake application servers
# and attaching them to HAProxy. The tests verify that the application servers are attached to the
# appropriate backend pools served by HAProxy.
#
- name: backend
  run_list:
  - recipe[fake::default]
  - recipe[rs-haproxy::frontend]
  attributes:
    cloud:
      provider: 'vagrant'
      public_ips: ['192.0.2.2']
    rs-haproxy:
      pools: ['test_example', 'appserver', 'example']
      stats_uri: '/haproxy-status'
      health_check_uri: '/'
      session_stickiness: true

      # Self-signed certificate used only for testing purposes
      ssl_cert: |
        -----BEGIN CERTIFICATE-----
        MIIDbTCCAlWgAwIBAgIJAPcgrJV5iiEYMA0GCSqGSIb3DQEBBQUAME0xCzAJBgNV
        BAYTAkNPMQswCQYDVQQIDAJTVDELMAkGA1UEBwwCTE8xDDAKBgNVBAoMA09SRzEW
        MBQGA1UEAwwNKi5leGFtcGxlLmNvbTAeFw0xNDA0MTEyMTEzNTBaFw0zNDA0MTAy
        MTEzNTBaME0xCzAJBgNVBAYTAkNPMQswCQYDVQQIDAJTVDELMAkGA1UEBwwCTE8x
        DDAKBgNVBAoMA09SRzEWMBQGA1UEAwwNKi5leGFtcGxlLmNvbTCCASIwDQYJKoZI
        hvcNAQEBBQADggEPADCCAQoCggEBALXP62NDGsnncMMDQxXOtj/bSfggHcuUxcXv
        EMo9mfrZXG5PXX9qPr0urQLGiK7tPgZYEFOKRTUB+y+0WVdzLR+lRfbPzTczbTm5
        SRtNB1AFir6TYsZe4BkIzroSVxm4lpEJmCerRv2cX7dWcSbHvfn+/wbDc+eDxX3Z
        fL2EwliNXTIFNJ4nZWl2XJpzz2oGiPVMkWxlXXo/76K/C4+MYHDXfl3mCcfT6UL9
        /5qFPC6AQzvSgTZWZVV6W6GrTx5leQBK+o48cHO/8KRQdKoQF0WX2cfu2SQ8Pe6B
        cCmPWAvvQtmcUBw9k2aJVkdp5sCpaahJ7Z0txJBTp8zxbqJVnIMCAwEAAaNQME4w
        HQYDVR0OBBYEFLR/S7W/CwXUdDPj3Ffj2zHSSGBxMB8GA1UdIwQYMBaAFLR/S7W/
        CwXUdDPj3Ffj2zHSSGBxMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEB
        ALIyDDHW2eB0wOT704SDCQ8+6UeTdgIGIELZ3cpayg5/JNO8kX8GnpgQYKwtTJFv
        I+8Of+POVMMnLeiMBMwCK1lknshz/ndzSoIreItQnocOHvLVY72LprD7p05BKswd
        1AGcQgNuJhYxcKldq1GT6ADOEL/2COldPW38lD5ledsBx8sWcIT5MrIAVyiLPGQK
        9IaZP+OokpHa8nTUfJXBvMe2dte5YPbkJUn7mYosA5eX3azjKtbpyFuDhOvGpyW4
        aHbYrCXzecd3pfjelCsyTWS+cbPJJpVwCLhQua+KC3wBge1uEohy9qDn0k/l9msa
        kgzzdJLOjdW1Sr3IAVJQ4Ag=
        -----END CERTIFICATE-----
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC1z+tjQxrJ53DD
        A0MVzrY/20n4IB3LlMXF7xDKPZn62VxuT11/aj69Lq0Cxoiu7T4GWBBTikU1Afsv
        tFlXcy0fpUX2z803M205uUkbTQdQBYq+k2LGXuAZCM66ElcZuJaRCZgnq0b9nF+3
        VnEmx735/v8Gw3Png8V92Xy9hMJYjV0yBTSeJ2Vpdlyac89qBoj1TJFsZV16P++i
        vwuPjGBw135d5gnH0+lC/f+ahTwugEM70oE2VmVVeluhq08eZXkASvqOPHBzv/Ck
        UHSqEBdFl9nH7tkkPD3ugXApj1gL70LZnFAcPZNmiVZHaebAqWmoSe2dLcSQU6fM
        8W6iVZyDAgMBAAECggEADdRP6k/7ZKo3GI5R9wGvOTI78SS4P3kEhibGFywSX1NT
        RYzB5uQ0+3zmahSh5vRiyGbAbypQU1TgP2OvfAhlwUd4B+sMiAtgXoiqd+onCT4y
        rIZXeBFVaHIUD3E/sNQql8OsEDBmCPpxCWgI2VNOLwrnaSNK2KxcRFNbuqqzgbq2
        G2OzPdAIC3IxvPbI3jOBoIT6HQltpeK3TQoDRGmX6am3tyx+cporcNOQVFuttqAo
        CsBWG2wSqZNo1PdS9cAeBoh85cNvMM8S5t9U37n8ZyZ1QKOghDi4SGadiqc3VjWm
        xhVKD4SCxWrSVpJvQ5qeT/KW4FBjqTf/L0WYoP6PAQKBgQDm+1adnJfXEoIDhc/j
        ib9muLdZkb5LTPxw5dZOX0I5nRAdAGPxviG8EIKrpIyD9vFs/YsKaaCsfDN0oMfk
        y9b/00eNluY3A+yREPSv4MYpNhyFzyTTeLQ8VcDxQjiqb4IfQ+oWy1nv8X1UidJo
        W6cCcpx3BjJZlz1E3XlT6dsyAwKBgQDJgTTmUmDHoFPBHabbcYoOkRSlfowGCoeU
        uuPlYIStuKGqwXvZH8xDICXrDGmx4oW2gt5morFna1MAQBjg8lCnkQZUqawkXoF6
        fOeea/xTyS9n8Y3uDhFNFLnSmNSmc3JGd8DnXWPn95webWNt20io6e92VoTk2zeK
        XI5y0FkjgQKBgQCcbA1mQ0vYzKHbfN0iPICwMduI/tgd6o7ybdPJ01zn42OsID2O
        0rHJyGyVjKPUIoGwy6tDa/DxnlLCYre8TAbXzN8iFdTl4PRt8UujZ9cKxahfPb60
        r4NvcKtvNudlFIrMXZPDyAaqJaI4g/VH0vmxAKjROhMS9Qb7AflOSIq2vQKBgGui
        j95DvJyFgJeUPi/T2znit1ObYDJN55RDrD43K0gcaobqqTwWpyZoArkmPUMey+vs
        xd2vI/IpOwHUOzXVWc3YQrhwlZorvR/vnk1aQ0OCIMd2GSlC7GzvGD9tEZID8tO/
        XhR4J0ieVA9QwR7KVmqb4ySkHIKesnE+9XxQ3HyBAoGAUf5iDIWBObupmpPKME+M
        AqwXAhfW0K5ON7uqW3N41NCCkDP+Zbr5e1eB3Hud/7pohcK+77QPAZ6mb/APDaya
        8av7fKKK4Y5T2PkVufR0aD09LX0T6K8heergtu/00N+MiCr/eIIqbPRQPdGoZ5v4
        MKNVXaQ/jcM58ZlZ0kuTzl4=
        -----END PRIVATE KEY-----
