---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 2
    memory: 1024
  network:
    - ["private_network", {ip: "33.33.33.5"}]

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: centos-6.4
  run_list:
  - recipe[yum::epel]
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list:
  - recipe[rs-haproxy::default]
  - recipe[rs-haproxy::tags]
  - recipe[rs-haproxy::collectd]
  attributes:
    rightscale:
      instance_uuid: '01-ABCDEFGH0123'
    cloud:
      provider: 'vagrant'
      public_ips: ['33.33.33.5']
    rs-haproxy:
      pools: ['app1', 'app2', 'app3', 'default']
      stats_uri: '/haproxy-status'
      statsuser: 'user'
      statspass: 'pass'
      health_check_uri: '/'
      session_stickiness: true
    rightscale:
      instance_uuid: '12345UUID'

- name: backend
  run_list:
  - recipe[fake::default]
  - recipe[rs-haproxy::frontend]
  provisioner:
    solo_rb:
      log_location: /var/log/chef-solo.log
  attributes:
    cloud:
      provider: 'vagrant'
      public_ips: ['33.33.33.5']
    rs-haproxy:
      pools: ['app1', 'app2', 'app3', 'default']
      stats_uri: '/haproxy-status'
      statsuser: 'user'
      statspass: 'pass'
      health_check_uri: '/'
      session_stickiness: true
    rightscale:
      instance_uuid: '12345UUID'
